Revert "Bump com.bmuschko.docker-remote-api from 9.0.1 to 9.1.0 (#1043)"
This reverts commit 36cba588128b46239c38cf921ab6d79e40483b0a.

Looks like there's an issue with the newer version:

```
Exception in thread "docker-java-stream--1183027921"
java.lang.UnsatisfiedLinkError: 'java.lang.String
com.bmuschko.gradle.docker.shaded.com.sun.jna.Native.getNativeVersion()'
```